/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

        &&HANDLE_DEPRECATED_LDLEXENV_PREF_NONE,
        &&HANDLE_DEPRECATED_POPLEXENV_PREF_NONE,
        &&HANDLE_DEPRECATED_GETITERATORNEXT_PREF_V8_V8,
        &&HANDLE_DEPRECATED_CREATEARRAYWITHBUFFER_PREF_IMM16,
        &&HANDLE_DEPRECATED_CREATEOBJECTWITHBUFFER_PREF_IMM16,
        &&HANDLE_DEPRECATED_TONUMBER_PREF_V8,
        &&HANDLE_DEPRECATED_TONUMERIC_PREF_V8,
        &&HANDLE_DEPRECATED_NEG_PREF_V8,
        &&HANDLE_DEPRECATED_NOT_PREF_V8,
        &&HANDLE_DEPRECATED_INC_PREF_V8,
        &&HANDLE_DEPRECATED_DEC_PREF_V8,
        &&HANDLE_DEPRECATED_CALLARG0_PREF_V8,
        &&HANDLE_DEPRECATED_CALLARG1_PREF_V8_V8,
        &&HANDLE_DEPRECATED_CALLARGS2_PREF_V8_V8_V8,
        &&HANDLE_DEPRECATED_CALLARGS3_PREF_V8_V8_V8_V8,
        &&HANDLE_DEPRECATED_CALLRANGE_PREF_IMM16_V8,
        &&HANDLE_DEPRECATED_CALLSPREAD_PREF_V8_V8_V8,
        &&HANDLE_DEPRECATED_CALLTHISRANGE_PREF_IMM16_V8,
        &&HANDLE_DEPRECATED_DEFINECLASSWITHBUFFER_PREF_ID16_IMM16_IMM16_V8_V8,
        &&HANDLE_DEPRECATED_RESUMEGENERATOR_PREF_V8,
        &&HANDLE_DEPRECATED_GETRESUMEMODE_PREF_V8,
        &&HANDLE_DEPRECATED_GETTEMPLATEOBJECT_PREF_V8,
        &&HANDLE_DEPRECATED_DELOBJPROP_PREF_V8_V8,
        &&HANDLE_DEPRECATED_SUSPENDGENERATOR_PREF_V8_V8,
        &&HANDLE_DEPRECATED_ASYNCFUNCTIONAWAITUNCAUGHT_PREF_V8_V8,
        &&HANDLE_DEPRECATED_COPYDATAPROPERTIES_PREF_V8_V8,
        &&HANDLE_DEPRECATED_SETOBJECTWITHPROTO_PREF_V8_V8,
        &&HANDLE_DEPRECATED_LDOBJBYVALUE_PREF_V8_V8,
        &&HANDLE_DEPRECATED_LDSUPERBYVALUE_PREF_V8_V8,
        &&HANDLE_DEPRECATED_LDOBJBYINDEX_PREF_V8_IMM32,
        &&HANDLE_DEPRECATED_ASYNCFUNCTIONRESOLVE_PREF_V8_V8_V8,
        &&HANDLE_DEPRECATED_ASYNCFUNCTIONREJECT_PREF_V8_V8_V8,
        &&HANDLE_DEPRECATED_STLEXVAR_PREF_IMM4_IMM4_V8,
        &&HANDLE_DEPRECATED_STLEXVAR_PREF_IMM8_IMM8_V8,
        &&HANDLE_DEPRECATED_STLEXVAR_PREF_IMM16_IMM16_V8,
        &&HANDLE_DEPRECATED_GETMODULENAMESPACE_PREF_ID32,
        &&HANDLE_DEPRECATED_STMODULEVAR_PREF_ID32,
        &&HANDLE_DEPRECATED_LDOBJBYNAME_PREF_ID32_V8,
        &&HANDLE_DEPRECATED_LDSUPERBYNAME_PREF_ID32_V8,
        &&HANDLE_DEPRECATED_LDMODULEVAR_PREF_ID32_IMM8,
        &&HANDLE_DEPRECATED_STCONSTTOGLOBALRECORD_PREF_ID32,
        &&HANDLE_DEPRECATED_STLETTOGLOBALRECORD_PREF_ID32,
        &&HANDLE_DEPRECATED_STCLASSTOGLOBALRECORD_PREF_ID32,
        &&HANDLE_DEPRECATED_LDHOMEOBJECT_PREF_NONE,
        &&HANDLE_DEPRECATED_CREATEOBJECTHAVINGMETHOD_PREF_IMM16,
        &&HANDLE_DEPRECATED_DYNAMICIMPORT_PREF_V8,
        &&HANDLE_DEPRECATED_ASYNCGENERATORREJECT_PREF_V8_V8,