/**
 * Copyright (c) 2021-2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Autogenerated file -- DO NOT EDIT!

#ifndef COMPILER_OPTIMIZER_TEMPLATES_SOURCE_LANGUAGES_H
#define COMPILER_OPTIMIZER_TEMPLATES_SOURCE_LANGUAGES_H

namespace panda::compiler {

enum class SourceLanguage : uint8_t {
    ECMASCRIPT = 0,
    PANDA_ASSEMBLY = 1
};

enum class AnyBaseType : uint32_t {
    UNDEFINED_TYPE = 0,
    ECMASCRIPT_HOLE_TYPE,
    ECMASCRIPT_NULL_TYPE,
    ECMASCRIPT_UNDEFINED_TYPE,
    ECMASCRIPT_INT_TYPE,
    ECMASCRIPT_DOUBLE_TYPE,
    ECMASCRIPT_OBJECT_TYPE,
    ECMASCRIPT_HEAP_OBJECT_TYPE,
    ECMASCRIPT_STRING_TYPE,
    ECMASCRIPT_ARRAY_TYPE,
    ECMASCRIPT_TRANSITION_TYPE,
    ECMASCRIPT_PROTOTYPE_TYPE,
    ECMASCRIPT_SPECIAL_INDEXED_TYPE,
    ECMASCRIPT_BOOLEAN_TYPE,
    COUNT
};

} // namespace panda::compiler

#endif // COMPILER_OPTIMIZER_TEMPLATES_SOURCE_LANGUAGES_H
